import {parseFile,analyze} from './sequence-features.mjs';
const $=id=>document.getElementById(id),names={length:'Length (residues)',charge_proxy:'K + R − D − E',hydrophobic_fraction:'Hydrophobic fraction',gravy:'GRAVY',molecular_weight:'Average molecular weight (Da)',aromatic_fraction:'Aromatic fraction',cysteines:'Cysteine count',entropy:'Normalized composition entropy'};
let parsed,records=[],filename='',known=new Map(),selectedRow;
const knownReady=fetch('atlas_complete.json').then(r=>r.json()).then(d=>{known=new Map(d.peptides.map(r=>[r.sequence,r]));}).catch(()=>{$('status').textContent='Existing structure catalog unavailable. File analysis still works.';});
for(const id of ['x','y','z','color'])for(const [value,label] of Object.entries(names))$(id).add(new Option(label,value));
$('x').value='length';$('y').value='charge_proxy';$('z').value='gravy';$('color').value='hydrophobic_fraction';
function options(el,labels){el.replaceChildren();labels.forEach((v,i)=>el.add(new Option(v,String(i))));}
async function load(text,name){filename=name;try{parsed=parseFile(text,name);$('columns').hidden=parsed.kind!=='table';if(parsed.kind==='table'){options($('seq-column'),parsed.headers);options($('id-column'),['Use row numbers',...parsed.headers]);const index=parsed.headers.findIndex(h=>/^(sequence|seq|peptide|amino_acid_sequence)$/i.test(h.trim()));if(index>=0)$('seq-column').value=index;$('status').textContent='Choose the sequence column, then analyze.';}else await run();}catch(e){$('status').textContent=e.message;$('workspace').hidden=true;}}
async function run(){try{const input=parsed.kind==='fasta'?parsed.records:parsed.rows.map((r,i)=>({id:+$('id-column').value?r[+$('id-column').value-1]:`row-${i+1}`,raw:r[+$('seq-column').value]}));if(input.length>50000)throw Error('Limit: 50,000 records. Split this file before importing.');if(input.some(r=>r.raw.length>10000))throw Error('Limit: 10,000 characters per sequence.');records=analyze(input);await knownReady;$('workspace').hidden=false;const valid=records.filter(r=>r.valid).length,dup=records.filter(r=>r.duplicate).length;$('status').textContent=`${filename}: ${records.length} records; ${valid} valid-alphabet sequences; ${records.length-valid} invalid/empty; ${dup} duplicate occurrences; ${records.filter(r=>r.normalized).length} normalized. ${records.filter(r=>r.valid&&(r.features.length<8||r.features.length>50)).length} outside length 8–50.`;options($('record'),records.map(r=>`${r.row}: ${r.id}`));if(records.length)show(records[0]);render();}catch(e){$('status').textContent=e.message;$('workspace').hidden=true;}}
function show(r){selectedRow=r.row;$('record').value=r.row-1;const f=r.features;$('detail').textContent=`${r.id}\nRow ${r.row}\n${r.sequence}\n\n${r.issues.join('; ')||'Alphabet, length and duplicate checks passed'}\n`+(f?'\n'+Object.entries(names).map(([key,label])=>`${label}: ${Number.isInteger(f[key])?f[key]:f[key].toFixed(4)}`).join('\n')+'\n\nComposition: '+Object.entries(f.counts).filter(([,n])=>n).map(([a,n])=>`${a}:${n}`).join(' '):'Features unavailable for invalid sequence.');const match=known.get(r.sequence);$('structure').hidden=!match;if(match)$('structure').href=`index.html#top=${match.rank}`;$('structure-note').textContent=match?`Exact match to top ${match.rank}. Existing Boltz prediction, not an experimental structure.`:'No existing structure match. This tool does not submit folding jobs.';}
function render(){const q=$('filter').value.trim().toUpperCase();const filtered=records.filter(r=>(!q||r.id.toUpperCase().includes(q)||r.sequence.includes(q))&&(!$('valid-length').checked||(r.valid&&r.features.length>=8&&r.features.length<=50))&&(!$('unique').checked||!r.duplicate));const plottable=filtered.filter(r=>r.valid);$('plot-count').textContent=`${plottable.length} plotted records. ${filtered.length-plottable.length} invalid/empty records excluded from the plot, retained in the report.`;
 const axis=id=>({title:{text:names[$(id).value]},gridcolor:'#405268',zerolinecolor:'#60748b'}),values=id=>plottable.map(r=>r.features[$(id).value]);const three=$('view').value==='3d';const trace={type:three?'scatter3d':'scattergl',mode:'markers',x:values('x'),y:values('y'),customdata:plottable.map(r=>r.row),marker:{size:three?4:7,color:values('color'),colorscale:'Viridis',showscale:true,colorbar:{title:{text:names[$('color').value]}}},hovertemplate:'Record %{customdata}<br>x=%{x}<br>y=%{y}<extra></extra>'};if(three)trace.z=values('z');Plotly.react('plot',[trace],{paper_bgcolor:'#0c121b',plot_bgcolor:'#0c121b',font:{color:'#dce8f7'},margin:{l:60,r:30,t:20,b:60},xaxis:axis('x'),yaxis:axis('y'),scene:{aspectmode:'cube',camera:{eye:{x:1.3,y:1.3,z:1.1}},xaxis:axis('x'),yaxis:axis('y'),zaxis:axis('z')},uirevision:[$('view').value,$('x').value,$('y').value,$('z').value].join('-')},{responsive:true,displaylogo:false});$('plot').removeAllListeners?.('plotly_click');$('plot').on('plotly_click',e=>show(records[e.points[0].customdata-1]));
 $('table').replaceChildren();for(const r of filtered.slice(0,200)){const tr=document.createElement('tr');for(const [i,v] of [r.row,r.id,r.sequence,r.features?.length??'—',r.issues.join('; ')||'Pass'].entries()){const td=document.createElement('td');if(i===0){const b=document.createElement('button');b.textContent=v;b.onclick=()=>show(r);td.append(b);}else td.textContent=v;tr.append(td);}$('table').append(tr);}$('table-note').textContent=`Showing first ${Math.min(filtered.length,200)} of ${filtered.length} filtered records. Use the selector or filter for others. Exports include every record.`;}
function save(data,type,name){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csvCell(v){let s=String(v??'');if(/^[=+@\-]/.test(s)&&typeof v!=='number')s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
$('download').onclick=()=>{const keys=Object.keys(names),header=['row','id','sequence','valid_alphabet','duplicate','normalized','issues',...keys,'existing_top100_rank'];const rows=records.map(r=>[r.row,r.id,r.sequence,r.valid,r.duplicate,r.normalized,r.issues.join('; '),...keys.map(k=>r.features?.[k]),known.get(r.sequence)?.rank??'']);save([header,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv','peptide-features.csv');};
$('report').onclick=()=>save(JSON.stringify({filename,created_at:new Date().toISOString(),method:'Uppercase; remove whitespace; canonical 20-AA alphabet; length 8–50; duplicates. No reference novelty or activity test.',records},null,2),'application/json','peptide-validation.json');
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;if(f.size>10*1024*1024){$('status').textContent='File exceeds 10 MB.';return;}await load(await f.text(),f.name);};$('analyze').onclick=run;$('record').onchange=()=>show(records[+$('record').value]);$('demo').onclick=async()=>{await knownReady;await load([...known.values()].map(r=>`>top${r.rank}\n${r.sequence}`).join('\n'),'top100.fasta');};
for(const id of ['x','y','z','color','view','valid-length','unique'])$(id).onchange=render;let timer;$('filter').oninput=()=>{clearTimeout(timer);timer=setTimeout(render,180);};
